'use client';

import {
  AlertTriangle, ArrowUpRight, BarChart3, Bell, Calculator, CheckCircle2,
  ChevronDown, CircleDollarSign, Copy, Download, FileText, FlaskConical,
  Menu, Moon, PackageOpen, Pencil, Plus, Search, Settings, ShoppingBasket,
  Sparkles, Sun, Trash2, TrendingUp, UtensilsCrossed, WalletCards, X,
} from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';

const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
type Kind = 'ingredient' | 'packaging' | 'expense' | 'recipe' | 'product';
type Stored<T> = T & { id: number };
type ApiRecord<T = Record<string, unknown>> = { id: number; kind: Kind; payload: T };
type Ingredient = { name: string; unit: string; qty: number; price: number; supplier: string; date: string; expiry: string };
type Packaging = { name: string; type: string; pack: number; price: number };
type Expense = { name: string; category: string; value: number };
type Recipe = { name: string; ingredients: number; yieldQty: number; yieldUnit: string; waste: number; cost: number; unit: number; notes: string };
type Product = { name: string; size: string; recipe: string; ingredientsCost: number; packagingCost: number; extras: number; labor: number; fees: number; cost: number; price: number; margin: number; profit: number; tone: string };

const nav = [
  { label: 'Visão geral', icon: BarChart3 }, { label: 'Ingredientes', icon: ShoppingBasket },
  { label: 'Embalagens', icon: PackageOpen }, { label: 'Receitas', icon: FlaskConical },
  { label: 'Produtos', icon: UtensilsCrossed }, { label: 'Despesas', icon: WalletCards },
  { label: 'Simulador', icon: Calculator }, { label: 'Relatórios', icon: FileText },
];

async function requestRecords<T = Record<string, unknown>>() {
  const response = await fetch('/api/records');
  if (!response.ok) throw new Error('Não foi possível carregar os dados.');
  return response.json() as Promise<ApiRecord<T>[]>;
}

function useRecords<T extends object>(kind: Kind) {
  const [items, setItems] = useState<Stored<T>[]>([]);
  const [loading, setLoading] = useState(true);
  const load = useCallback(async () => {
    setLoading(true);
    try {
      const records = await requestRecords<T>();
      setItems(records.filter((record) => record.kind === kind).map((record) => ({ ...record.payload, id: record.id })));
    } finally { setLoading(false); }
  }, [kind]);
  useEffect(() => { load().catch(() => setLoading(false)); }, [load]);

  async function save(payload: T, id?: number) {
    const response = await fetch('/api/records', { method: id ? 'PUT' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(id ? { id, payload } : { kind, payload }) });
    if (!response.ok) throw new Error('Não foi possível salvar.');
    const record = await response.json() as ApiRecord<T>;
    const saved = { ...record.payload, id: record.id } as Stored<T>;
    setItems((current) => id ? current.map((item) => item.id === id ? saved : item) : [saved, ...current]);
    return saved;
  }
  async function remove(id: number) {
    const response = await fetch('/api/records', { method: 'DELETE', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id }) });
    if (!response.ok) throw new Error('Não foi possível excluir.');
    setItems((current) => current.filter((item) => item.id !== id));
  }
  return { items, loading, save, remove };
}

export default function Home() {
  const [dark, setDark] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [activeView, setActiveView] = useState('Visão geral');
  const [allRecords, setAllRecords] = useState<ApiRecord[]>([]);
  useEffect(() => { document.documentElement.classList.toggle('dark', dark); }, [dark]);
  useEffect(() => { if (activeView === 'Visão geral') requestRecords().then(setAllRecords).catch(() => setAllRecords([])); }, [activeView]);

  const dashboardProducts = allRecords.filter((record) => record.kind === 'product').map((record) => ({ ...record.payload, id: record.id } as Stored<Product>));
  const dashboardIngredients = allRecords.filter((record) => record.kind === 'ingredient');
  const dashboardExpenses = allRecords.filter((record) => record.kind === 'expense').map((record) => record.payload as Expense);
  const average = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0;
  const switchView = (label: string) => { setActiveView(label); setMobileOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }); };

  return <main className="min-h-screen bg-background text-foreground">
    <aside className={`sidebar-shell ${mobileOpen ? 'sidebar-open' : ''}`}>
      <div className="brand-row"><div className="brand-mark"><Sparkles size={19} /></div><div><p className="brand-name">Doce Margem</p><p className="brand-kicker">Gestão de preços</p></div><button className="mobile-close" onClick={() => setMobileOpen(false)} aria-label="Fechar menu"><X size={20} /></button></div>
      <nav className="main-nav" aria-label="Navegação principal"><p className="nav-label">Minha operação</p>{nav.map(({ label, icon: Icon }) => <button key={label} onClick={() => switchView(label)} className={`nav-item ${activeView === label ? 'active' : ''}`}><Icon size={18} /><span>{label}</span>{label === 'Ingredientes' && <span className="nav-count">{dashboardIngredients.length}</span>}</button>)}</nav>
      <div className="sidebar-footer"><div className="monthly-card"><span className="mini-icon"><TrendingUp size={15} /></span><p>Resultado cadastrado</p><strong>{money.format(dashboardProducts.reduce((sum, item) => sum + item.profit, 0))}</strong><small>{dashboardProducts.length} produtos ativos</small></div><button className="nav-item"><Settings size={18} /><span>Configurações</span></button></div>
    </aside>
    {mobileOpen && <button className="sidebar-backdrop" aria-label="Fechar menu" onClick={() => setMobileOpen(false)} />}
    <nav className="mobile-dock" aria-label="Navegação rápida">{[
      { label: 'Visão geral', short: 'Início', icon: BarChart3 }, { label: 'Ingredientes', short: 'Insumos', icon: ShoppingBasket },
      { label: 'Produtos', short: 'Produtos', icon: UtensilsCrossed }, { label: 'Simulador', short: 'Simular', icon: Calculator },
    ].map(({ label, short, icon: Icon }) => <button key={label} className={activeView === label ? 'active' : ''} onClick={() => switchView(label)}><Icon size={20} /><span>{short}</span></button>)}<button onClick={() => setMobileOpen(true)}><Menu size={20} /><span>Mais</span></button></nav>

    <section className="app-content">
      <header className="topbar"><button className="icon-button menu-button" onClick={() => setMobileOpen(true)} aria-label="Abrir menu"><Menu size={20} /></button><div className="mobile-page-title"><span>Doce Margem</span><strong>{activeView}</strong></div><div className="search-box"><Search size={17} /><input aria-label="Buscar" placeholder="Buscar receitas, produtos, insumos..." /><kbd>⌘ K</kbd></div><div className="topbar-actions"><button className="icon-button" aria-label="Alternar tema" onClick={() => setDark(!dark)}>{dark ? <Sun size={18} /> : <Moon size={18} />}</button><button className="icon-button notification-button" aria-label="Notificações"><Bell size={18} /></button><div className="user-chip"><div className="avatar">GM</div><div><strong>Gustavo</strong><small>Administrador</small></div><ChevronDown size={15} /></div></div></header>
      <div className="page-wrap">{activeView === 'Visão geral' ? <Dashboard products={dashboardProducts} ingredients={dashboardIngredients.length} expenses={dashboardExpenses} onNavigate={switchView} average={average} /> : <ModuleRouter view={activeView} />}</div>
    </section>
  </main>;
}

function Dashboard({ products, ingredients, expenses, onNavigate, average }: { products: Stored<Product>[]; ingredients: number; expenses: Expense[]; onNavigate: (view: string) => void; average: (values: number[]) => number }) {
  const totalFixed = expenses.reduce((sum, item) => sum + item.value, 0);
  return <>
    <div className="page-heading"><div><p className="eyebrow">PRONTO PARA O USO REAL</p><h1>Sua operação começa aqui.</h1><p>Cadastre seus custos reais para construir preços seguros e lucrativos.</p></div><Button onClick={() => onNavigate('Produtos')} className="primary-action"><Plus size={17} /> Novo produto</Button></div>
    <div className="alert-strip"><div className="alert-icon"><Sparkles size={19} /></div><div><strong>{ingredients ? `${ingredients} insumos cadastrados` : 'Base zerada com sucesso'}</strong><p>{ingredients ? 'Seus dados reais já estão entrando nos cálculos.' : 'Comece por ingredientes, receitas e produtos. Nada de demonstração será misturado aos seus números.'}</p></div><button onClick={() => onNavigate('Ingredientes')}>Começar <ArrowUpRight size={15} /></button></div>
    <section className="metric-grid" aria-label="Indicadores principais">
      <Metric icon={<CircleDollarSign size={20} />} label="Preços cadastrados" value={money.format(products.reduce((sum, item) => sum + item.price, 0))} detail={`${products.length} produtos`} tone="rose" />
      <Metric icon={<WalletCards size={20} />} label="Custo médio por produto" value={money.format(average(products.map((item) => item.cost)))} detail="Calculado com dados reais" tone="cream" />
      <Metric icon={<TrendingUp size={20} />} label="Margem média" value={`${average(products.map((item) => item.margin)).toFixed(1).replace('.', ',')}%`} detail="Média do portfólio" tone="sage" />
      <Metric icon={<UtensilsCrossed size={20} />} label="Despesas mensais" value={money.format(totalFixed)} detail={`${expenses.length} despesas cadastradas`} tone="lilac" />
    </section>
    <section className="dashboard-grid"><article className="panel performance-panel"><div className="panel-header"><div><p className="section-kicker">PORTFÓLIO</p><h2>Custo, preço e lucro</h2></div></div>{products.length ? <div className="bar-chart compact-bars">{products.slice(0, 6).map((product) => { const scale = Math.max(product.price, 1); return <div className="bar-month" key={product.id}><div className="bar-group"><span className="bar cost" style={{ height: `${product.cost / scale * 80}%` }} /><span className="bar revenue" style={{ height: '80%' }} /><span className="bar profit" style={{ height: `${product.profit / scale * 80}%` }} /></div><small>{product.name.slice(0, 8)}</small></div>; })}</div> : <EmptyState icon={<BarChart3 />} title="Sem produtos ainda" text="O gráfico aparecerá assim que você cadastrar seu primeiro produto." action="Cadastrar produto" onAction={() => onNavigate('Produtos')} />}</article>
      <article className="panel quick-panel"><div className="panel-header"><div><p className="section-kicker">ATALHOS</p><h2>Monte sua base real</h2></div></div><QuickLink onClick={() => onNavigate('Ingredientes')} icon={<ShoppingBasket size={19} />} tone="green" title="Cadastrar insumos" detail="Registre preços e fornecedores" /><QuickLink onClick={() => onNavigate('Receitas')} icon={<FlaskConical size={19} />} tone="gold" title="Criar receita" detail="Monte a ficha técnica" /><QuickLink onClick={() => onNavigate('Simulador')} icon={<Calculator size={19} />} tone="rose" title="Simular preço" detail="Teste margem e desconto" /></article></section>
    <section className="panel products-panel"><div className="panel-header"><div><p className="section-kicker">PRODUTOS</p><h2>Rentabilidade cadastrada</h2></div><button className="text-button" onClick={() => onNavigate('Produtos')}>Gerenciar <ArrowUpRight size={15} /></button></div>{products.length ? <ProductTable items={products} readOnly /> : <EmptyState icon={<UtensilsCrossed />} title="Seu portfólio está vazio" text="Cadastre o primeiro produto para acompanhar custo, margem e lucro." action="Novo produto" onAction={() => onNavigate('Produtos')} />}</section>
  </>;
}

function Metric({ icon, label, value, detail, tone }: { icon: React.ReactNode; label: string; value: string; detail: string; tone: string }) { return <article className="metric-card"><div className={`metric-icon ${tone}`}>{icon}</div><div><p>{label}</p><strong>{value}</strong><small>{detail}</small></div></article>; }
function QuickLink({ icon, tone, title, detail, onClick }: { icon: React.ReactNode; tone: string; title: string; detail: string; onClick: () => void }) { return <button onClick={onClick} className="quick-link"><span className={`quick-icon ${tone}`}>{icon}</span><div><strong>{title}</strong><small>{detail}</small></div><ArrowUpRight size={17} /></button>; }
function EmptyState({ icon, title, text, action, onAction }: { icon: React.ReactNode; title: string; text: string; action?: string; onAction?: () => void }) { return <div className="empty-state"><span>{icon}</span><strong>{title}</strong><p>{text}</p>{action && <button onClick={onAction}><Plus size={14} /> {action}</button>}</div>; }
function ModuleHeading({ eyebrow, title, subtitle, action }: { eyebrow: string; title: string; subtitle: string; action?: React.ReactNode }) { return <div className="page-heading module-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>; }
function RowActions({ onEdit, onDelete, onDuplicate }: { onEdit?: () => void; onDelete?: () => void; onDuplicate?: () => void }) { return <div className="row-actions">{onEdit && <button aria-label="Editar" onClick={onEdit}><Pencil size={14} /></button>}{onDuplicate && <button aria-label="Duplicar" onClick={onDuplicate}><Copy size={14} /></button>}{onDelete && <button className="danger" aria-label="Excluir" onClick={onDelete}><Trash2 size={14} /></button>}</div>; }
function confirmDelete(callback: () => void) { if (window.confirm('Excluir este registro permanentemente?')) callback(); }

function ModuleRouter({ view }: { view: string }) {
  if (view === 'Ingredientes') return <IngredientsView />;
  if (view === 'Embalagens') return <PackagingView />;
  if (view === 'Despesas') return <ExpensesView />;
  if (view === 'Receitas') return <RecipesView />;
  if (view === 'Produtos') return <ProductsView />;
  if (view === 'Simulador') return <SimulatorView />;
  return <ReportsView />;
}

function IngredientsView() {
  const records = useRecords<Ingredient>('ingredient'); const [editing, setEditing] = useState<Stored<Ingredient> | null>(null); const [saved, setSaved] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const item: Ingredient = { name: String(form.get('name')), unit: String(form.get('unit')), qty: Number(form.get('qty')), price: Number(form.get('price')), supplier: String(form.get('supplier')), date: editing?.date || new Date().toLocaleDateString('pt-BR'), expiry: String(form.get('expiry')) }; await records.save(item, editing?.id); setEditing(null); formElement.reset(); setSaved(true); setTimeout(() => setSaved(false), 1800); }
  return <><ModuleHeading eyebrow="CADASTRO" title="Ingredientes e compras" subtitle="Registre apenas seus insumos reais, com fornecedor, validade e custo fracionado." />{saved && <SaveToast text="Ingrediente salvo" />}<div className="module-layout"><EditorPanel title={editing ? 'Editar ingrediente' : 'Novo ingrediente'} editing={!!editing} onCancel={() => setEditing(null)}><form key={editing?.id || 'new'} onSubmit={submit} className="data-form"><label>Nome<input name="name" required defaultValue={editing?.name} placeholder="Ex.: Leite condensado" /></label><div className="form-row"><label>Unidade de compra<input name="unit" required defaultValue={editing?.unit} placeholder="Ex.: caixa 395 g" /></label><label>Quantidade comprada<input name="qty" type="number" step="0.01" required defaultValue={editing?.qty} /></label></div><div className="form-row"><label>Preço pago<input name="price" type="number" step="0.01" required defaultValue={editing?.price} /></label><label>Fornecedor<input name="supplier" required defaultValue={editing?.supplier} /></label></div><label>Validade<input name="expiry" type="month" defaultValue={editing?.expiry} /></label><SaveButton editing={!!editing} /></form></EditorPanel><section className="panel data-panel"><DataHeader title={`${records.items.length} ingredientes`} />{records.loading ? <Loading /> : records.items.length ? <IngredientTable items={records.items} onEdit={setEditing} onDelete={(id) => confirmDelete(() => records.remove(id))} /> : <EmptyState icon={<ShoppingBasket />} title="Nenhum ingrediente" text="Cadastre o primeiro insumo para iniciar os cálculos." />}</section></div></>;
}

function PackagingView() {
  const records = useRecords<Packaging>('packaging'); const [editing, setEditing] = useState<Stored<Packaging> | null>(null);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); await records.save({ name: String(form.get('name')), type: String(form.get('type')), pack: Number(form.get('pack')), price: Number(form.get('price')) }, editing?.id); setEditing(null); formElement.reset(); }
  return <><ModuleHeading eyebrow="CADASTRO" title="Embalagens e adicionais" subtitle="Gerencie potes, tampas, colheres, etiquetas e extras com custo unitário real." /><div className="module-layout"><EditorPanel title={editing ? 'Editar embalagem' : 'Nova embalagem'} editing={!!editing} onCancel={() => setEditing(null)}><form key={editing?.id || 'new'} onSubmit={submit} className="data-form"><label>Nome<input name="name" required defaultValue={editing?.name} /></label><div className="form-row"><label>Categoria<input name="type" required defaultValue={editing?.type} /></label><label>Quantidade no pacote<input name="pack" type="number" step="0.01" required defaultValue={editing?.pack} /></label></div><label>Preço pago<input name="price" type="number" step="0.01" required defaultValue={editing?.price} /></label><SaveButton editing={!!editing} /></form></EditorPanel><section className="panel data-panel"><DataHeader title={`${records.items.length} embalagens`} />{records.loading ? <Loading /> : records.items.length ? <PackagingTable items={records.items} onEdit={setEditing} onDelete={(id) => confirmDelete(() => records.remove(id))} /> : <EmptyState icon={<PackageOpen />} title="Nenhuma embalagem" text="Adicione o primeiro item de embalagem." />}</section></div></>;
}

function ExpensesView() {
  const records = useRecords<Expense>('expense'); const [editing, setEditing] = useState<Stored<Expense> | null>(null); const total = records.items.reduce((sum, item) => sum + item.value, 0);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); await records.save({ name: String(form.get('name')), category: String(form.get('category')), value: Number(form.get('value')) }, editing?.id); setEditing(null); formElement.reset(); }
  return <><ModuleHeading eyebrow="ESTRUTURA" title="Despesas fixas e rateio" subtitle="Mantenha os gastos mensais atualizados para formar preços sustentáveis." /><div className="module-layout"><EditorPanel title={editing ? 'Editar despesa' : 'Nova despesa'} editing={!!editing} onCancel={() => setEditing(null)}><form key={editing?.id || 'new'} onSubmit={submit} className="data-form"><label>Nome<input name="name" required defaultValue={editing?.name} /></label><label>Categoria<input name="category" required defaultValue={editing?.category} /></label><label>Valor mensal<input name="value" type="number" step="0.01" required defaultValue={editing?.value} /></label><SaveButton editing={!!editing} /></form></EditorPanel><section className="panel data-panel"><div className="panel-header"><DataHeader title={money.format(total)} /><span className="rate-badge">{money.format(total / 650)} / unidade</span></div>{records.loading ? <Loading /> : records.items.length ? <ExpenseTable items={records.items} onEdit={setEditing} onDelete={(id) => confirmDelete(() => records.remove(id))} /> : <EmptyState icon={<WalletCards />} title="Nenhuma despesa" text="Cadastre aluguel, energia, pró-labore e demais gastos." />}</section></div></>;
}

function RecipesView() {
  const records = useRecords<Recipe>('recipe'); const [editing, setEditing] = useState<Stored<Recipe> | null>(null);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const cost = Number(form.get('cost')); const yieldQty = Number(form.get('yieldQty')); const waste = Number(form.get('waste')); await records.save({ name: String(form.get('name')), ingredients: Number(form.get('ingredients')), yieldQty, yieldUnit: String(form.get('yieldUnit')), waste, cost: cost * (1 + waste / 100), unit: yieldQty ? cost * (1 + waste / 100) / yieldQty : 0, notes: String(form.get('notes')) }, editing?.id); setEditing(null); formElement.reset(); }
  function duplicate(recipe: Stored<Recipe>) { const { id: _id, ...copy } = recipe; return records.save({ ...copy, name: `${recipe.name} (cópia)` }); }
  return <><ModuleHeading eyebrow="FICHAS TÉCNICAS" title="Receitas" subtitle="Crie e edite fichas com rendimento, perdas, observações e custo unitário." /><div className="module-layout"><EditorPanel title={editing ? 'Editar receita' : 'Nova receita'} editing={!!editing} onCancel={() => setEditing(null)}><form key={editing?.id || 'new'} onSubmit={submit} className="data-form"><label>Nome<input name="name" required defaultValue={editing?.name} /></label><div className="form-row"><label>Nº de ingredientes<input name="ingredients" type="number" required defaultValue={editing?.ingredients || 1} /></label><label>Custo dos ingredientes<input name="cost" type="number" step="0.01" required defaultValue={editing?.cost} /></label></div><div className="form-row"><label>Rendimento<input name="yieldQty" type="number" step="0.01" required defaultValue={editing?.yieldQty} /></label><label>Unidade<select name="yieldUnit" defaultValue={editing?.yieldUnit || 'g'}><option value="g">gramas</option><option value="ml">mililitros</option><option value="porções">porções</option></select></label></div><label>Perda (%)<input name="waste" type="number" step="0.1" defaultValue={editing?.waste || 0} /></label><label>Observações<textarea name="notes" defaultValue={editing?.notes} /></label><SaveButton editing={!!editing} /></form></EditorPanel><section className="panel data-panel"><DataHeader title={`${records.items.length} receitas`} />{records.loading ? <Loading /> : records.items.length ? <div className="recipe-list">{records.items.map((recipe) => <article className="recipe-card" key={recipe.id}><div className="recipe-top"><span className="recipe-glyph"><FlaskConical size={18} /></span><div><strong>{recipe.name}</strong><small>{recipe.ingredients} ingredientes · {recipe.yieldQty} {recipe.yieldUnit}</small></div><RowActions onEdit={() => setEditing(recipe)} onDuplicate={() => duplicate(recipe)} onDelete={() => confirmDelete(() => records.remove(recipe.id))} /></div><div className="recipe-metrics"><span><small>Custo total</small><strong>{money.format(recipe.cost)}</strong></span><span><small>Custo unitário</small><strong>{money.format(recipe.unit)}</strong></span><span><small>Perda</small><strong>{recipe.waste}%</strong></span></div></article>)}</div> : <EmptyState icon={<FlaskConical />} title="Nenhuma receita" text="Monte sua primeira ficha técnica." />}</section></div></>;
}

function ProductsView() {
  const records = useRecords<Product>('product'); const recipes = useRecords<Recipe>('recipe'); const [editing, setEditing] = useState<Stored<Product> | null>(null);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const ingredientsCost = Number(form.get('ingredientsCost')); const packagingCost = Number(form.get('packagingCost')); const extras = Number(form.get('extras')); const labor = Number(form.get('labor')); const fees = Number(form.get('fees')); const margin = Number(form.get('margin')); const cost = ingredientsCost + packagingCost + extras + labor + fees; const price = margin < 100 ? cost / (1 - margin / 100) : cost; await records.save({ name: String(form.get('name')), size: String(form.get('size')), recipe: String(form.get('recipe')), ingredientsCost, packagingCost, extras, labor, fees, cost, price, margin, profit: price - cost, tone: editing?.tone || 'berry' }, editing?.id); setEditing(null); formElement.reset(); }
  function duplicate(product: Stored<Product>) { const { id: _id, ...copy } = product; return records.save({ ...copy, name: `${product.name} (cópia)` }); }
  return <><ModuleHeading eyebrow="PRECIFICAÇÃO" title="Produtos finais" subtitle="Edite qualquer componente de custo e recalcule o preço sugerido." /><div className="module-layout"><EditorPanel title={editing ? 'Editar produto' : 'Novo produto'} editing={!!editing} onCancel={() => setEditing(null)}><form key={editing?.id || 'new'} onSubmit={submit} className="data-form"><div className="form-row"><label>Nome<input name="name" required defaultValue={editing?.name} /></label><label>Tamanho<input name="size" required defaultValue={editing?.size} /></label></div><label>Receita base<select name="recipe" defaultValue={editing?.recipe}>{recipes.items.length ? recipes.items.map((recipe) => <option key={recipe.id} value={recipe.name}>{recipe.name}</option>) : <option value="">Sem receita cadastrada</option>}</select></label><div className="form-row"><label>Custo da receita<input name="ingredientsCost" type="number" step="0.01" required defaultValue={editing?.ingredientsCost} /></label><label>Embalagem<input name="packagingCost" type="number" step="0.01" required defaultValue={editing?.packagingCost || 0} /></label></div><div className="form-row"><label>Adicionais<input name="extras" type="number" step="0.01" defaultValue={editing?.extras || 0} /></label><label>Mão de obra<input name="labor" type="number" step="0.01" defaultValue={editing?.labor || 0} /></label></div><div className="form-row"><label>Taxas em reais<input name="fees" type="number" step="0.01" defaultValue={editing?.fees || 0} /></label><label>Margem desejada (%)<input name="margin" type="number" step="0.1" max="95" required defaultValue={editing?.margin || 50} /></label></div><SaveButton editing={!!editing} /></form></EditorPanel><section className="panel data-panel"><DataHeader title={`${records.items.length} produtos`} />{records.loading ? <Loading /> : records.items.length ? <ProductTable items={records.items} onEdit={setEditing} onDuplicate={duplicate} onDelete={(id) => confirmDelete(() => records.remove(id))} /> : <EmptyState icon={<UtensilsCrossed />} title="Nenhum produto" text="Cadastre o primeiro produto final." />}</section></div></>;
}

function EditorPanel({ title, editing, onCancel, children }: { title: string; editing: boolean; onCancel: () => void; children: React.ReactNode }) { return <section className="panel form-panel"><div className="panel-header"><div><p className="section-kicker">{editing ? 'MODO DE EDIÇÃO' : 'NOVO REGISTRO'}</p><h2>{title}</h2></div>{editing && <button className="cancel-edit" onClick={onCancel}><X size={14} /> Cancelar</button>}</div>{children}</section>; }
function SaveButton({ editing }: { editing: boolean }) { return <Button type="submit" className="form-submit">{editing ? <Pencil size={16} /> : <Plus size={16} />}{editing ? 'Salvar alterações' : 'Salvar registro'}</Button>; }
function SaveToast({ text }: { text: string }) { return <div className="save-toast"><CheckCircle2 size={16} /> {text}</div>; }
function DataHeader({ title }: { title: string }) { return <div><p className="section-kicker">DADOS REAIS</p><h2>{title}</h2></div>; }
function Loading() { return <div className="loading-state">Carregando dados...</div>; }

function IngredientTable({ items, onEdit, onDelete }: { items: Stored<Ingredient>[]; onEdit: (item: Stored<Ingredient>) => void; onDelete: (id: number) => void }) { return <div className="product-table-wrap"><table><thead><tr><th>Ingrediente</th><th>Compra</th><th>Custo fracionado</th><th>Fornecedor</th><th>Validade</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.unit} · {money.format(item.price)}</td><td className="profit-value">{money.format(item.qty ? item.price / item.qty : 0)} / un.</td><td>{item.supplier}</td><td>{item.expiry || '—'}</td><td><RowActions onEdit={() => onEdit(item)} onDelete={() => onDelete(item.id)} /></td></tr>)}</tbody></table></div>; }
function PackagingTable({ items, onEdit, onDelete }: { items: Stored<Packaging>[]; onEdit: (item: Stored<Packaging>) => void; onDelete: (id: number) => void }) { return <div className="product-table-wrap"><table><thead><tr><th>Item</th><th>Tipo</th><th>Pacote</th><th>Preço</th><th>Custo unitário</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.type}</td><td>{item.pack} un.</td><td>{money.format(item.price)}</td><td className="profit-value">{money.format(item.pack ? item.price / item.pack : 0)}</td><td><RowActions onEdit={() => onEdit(item)} onDelete={() => onDelete(item.id)} /></td></tr>)}</tbody></table></div>; }
function ExpenseTable({ items, onEdit, onDelete }: { items: Stored<Expense>[]; onEdit: (item: Stored<Expense>) => void; onDelete: (id: number) => void }) { return <div className="product-table-wrap"><table><thead><tr><th>Despesa</th><th>Categoria</th><th>Valor mensal</th><th>Rateio / 650 un.</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.category}</td><td>{money.format(item.value)}</td><td>{money.format(item.value / 650)}</td><td><RowActions onEdit={() => onEdit(item)} onDelete={() => onDelete(item.id)} /></td></tr>)}</tbody></table></div>; }
function ProductTable({ items, onEdit, onDelete, onDuplicate, readOnly = false }: { items: Stored<Product>[]; onEdit?: (item: Stored<Product>) => void; onDelete?: (id: number) => void; onDuplicate?: (item: Stored<Product>) => void; readOnly?: boolean }) { return <div className="product-table-wrap"><table><thead><tr><th>Produto</th><th>Custo</th><th>Preço sugerido</th><th>Lucro</th><th>Margem</th>{!readOnly && <th />}</tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small className="table-subtitle">{item.size}</small></td><td>{money.format(item.cost)}</td><td><strong>{money.format(item.price)}</strong></td><td className="profit-value">{money.format(item.profit)}</td><td><span className="margin-pill">{item.margin.toFixed(1).replace('.', ',')}%</span></td>{!readOnly && <td><RowActions onEdit={() => onEdit?.(item)} onDuplicate={() => onDuplicate?.(item)} onDelete={() => onDelete?.(item.id)} /></td>}</tr>)}</tbody></table></div>; }

function SimulatorView() {
  const [margin, setMargin] = useState(55); const [ingredientCost, setIngredientCost] = useState(0); const [packagingCost, setPackagingCost] = useState(0); const [labor, setLabor] = useState(0); const [variableRate, setVariableRate] = useState(0); const [discount, setDiscount] = useState(0); const [fixedIncluded, setFixedIncluded] = useState(false); const expenses = useRecords<Expense>('expense'); const fixedUnit = fixedIncluded ? expenses.items.reduce((sum, item) => sum + item.value, 0) / 650 : 0; const baseCost = ingredientCost + packagingCost + labor + fixedUnit; const denominator = 1 - margin / 100 - variableRate / 100; const salePrice = denominator > 0 ? baseCost / denominator : 0; const finalPrice = salePrice * (1 - discount / 100); const contribution = finalPrice - ingredientCost - packagingCost - labor - finalPrice * variableRate / 100; const profit = finalPrice - baseCost - finalPrice * variableRate / 100; const markup = baseCost ? finalPrice / baseCost : 0;
  return <><ModuleHeading eyebrow="LABORATÓRIO" title="Simulador" subtitle="Teste seus números reais sem alterar os produtos cadastrados." /><div className="simulator-layout"><section className="panel simulator-controls"><div className="panel-header"><DataHeader title="Ajuste as variáveis" /></div><RangeField label="Margem desejada" value={margin} min={10} max={80} suffix="%" onChange={setMargin} /><RangeField label="Custo da receita" value={ingredientCost} min={0} max={100} step={.1} prefix="R$" onChange={setIngredientCost} /><RangeField label="Custo da embalagem" value={packagingCost} min={0} max={30} step={.1} prefix="R$" onChange={setPackagingCost} /><RangeField label="Mão de obra" value={labor} min={0} max={50} step={.1} prefix="R$" onChange={setLabor} /><RangeField label="Taxas variáveis" value={variableRate} min={0} max={25} suffix="%" onChange={setVariableRate} /><RangeField label="Desconto" value={discount} min={0} max={40} suffix="%" onChange={setDiscount} /><label className="toggle-line"><span><strong>Incluir despesas fixas</strong><small>{money.format(fixedUnit)} por unidade</small></span><input type="checkbox" checked={fixedIncluded} onChange={(event) => setFixedIncluded(event.target.checked)} /></label></section><section className="simulator-result"><div className="price-orbit"><small>PREÇO SUGERIDO</small><strong>{money.format(finalPrice)}</strong><span>por unidade</span></div><div className="result-grid"><Result label="Custo total" value={money.format(baseCost)} /><Result label="Lucro unitário" value={money.format(profit)} positive /><Result label="Contribuição" value={money.format(contribution)} /><Result label="Markup" value={`${markup.toFixed(2).replace('.', ',')}×`} /></div><div className="health-banner"><TrendingUp size={18} /><div><strong>{baseCost ? 'Simulação atualizada' : 'Informe os custos'}</strong><small>{baseCost ? 'O preço reflete todos os valores informados.' : 'Comece pelo custo da receita.'}</small></div></div></section></div></>;
}
function RangeField({ label, value, min, max, step = 1, prefix, suffix, onChange }: { label: string; value: number; min: number; max: number; step?: number; prefix?: string; suffix?: string; onChange: (value: number) => void }) { return <label className="range-field"><span><strong>{label}</strong><output>{prefix ? `${prefix} ` : ''}{value.toFixed(step < 1 ? 2 : 0).replace('.', ',')}{suffix}</output></span><input type="range" min={min} max={max} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} /></label>; }
function Result({ label, value, positive }: { label: string; value: string; positive?: boolean }) { return <div className="result-item"><small>{label}</small><strong className={positive ? 'profit-value' : ''}>{value}</strong></div>; }

function ReportsView() {
  const products = useRecords<Product>('product'); const reports = [{ title: 'Fichas técnicas', detail: 'Ingredientes, rendimento e custo por porção', icon: FlaskConical }, { title: 'Custos por produto', detail: 'Composição completa do custo unitário', icon: Calculator }, { title: 'Margens e lucratividade', detail: 'Preço, contribuição e lucro por item', icon: TrendingUp }, { title: 'Histórico de compras', detail: 'Preços e fornecedores cadastrados', icon: ShoppingBasket }];
  function csv() { const rows = [['Produto', 'Custo', 'Preço', 'Margem', 'Lucro'], ...products.items.map((item) => [item.name, item.cost, item.price, item.margin, item.profit])]; const blob = new Blob([`\uFEFF${rows.map((row) => row.join(';')).join('\n')}`], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'doce-margem-relatorio.csv'; anchor.click(); URL.revokeObjectURL(url); }
  return <><ModuleHeading eyebrow="ANÁLISE" title="Relatórios" subtitle="Exporte somente os dados reais da sua operação." action={<Button onClick={csv} className="primary-action"><Download size={16} /> Exportar CSV</Button>} /><section className="report-grid">{reports.map(({ title, detail, icon: Icon }) => <article className="panel report-card" key={title}><span><Icon size={21} /></span><div><h2>{title}</h2><p>{detail}</p></div><div className="report-actions"><button onClick={() => window.print()}><FileText size={15} /> Salvar PDF</button><button onClick={csv}><Download size={15} /> CSV</button></div></article>)}</section><section className="panel report-preview"><div className="panel-header"><DataHeader title="Lucratividade do portfólio" /><span className="rate-badge">Dados reais</span></div>{products.items.length ? <ProductTable items={products.items} readOnly /> : <EmptyState icon={<FileText />} title="Sem dados para o relatório" text="Cadastre produtos para gerar sua análise." />}</section></>;
}
