-- Additive adapter for the existing JSON record contract. No legacy table is removed.
create table public.audit_records (
 id bigint generated by default as identity primary key,
 store_id uuid not null references public.stores(id),
 kind text not null check(kind in ('ingredient','packaging','expense','recipe','product','sale','supplier','scenario','settings')),
 payload jsonb not null check(jsonb_typeof(payload)='object'),
 request_key uuid,
 legacy_key text,
 created_by uuid not null default auth.uid() references auth.users(id),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(store_id,request_key), unique(store_id,legacy_key)
);
create index audit_records_store_kind_idx on public.audit_records(store_id,kind,id);
alter table public.audit_records enable row level security;
revoke all on public.audit_records from anon;
grant select,insert,update,delete on public.audit_records to authenticated;
grant usage on sequence public.audit_records_id_seq to authenticated;
create policy records_read on public.audit_records for select to authenticated using(public.is_store_member(store_id));
create policy records_create on public.audit_records for insert to authenticated
 with check(public.has_store_role(store_id,array['admin','employee']::public.app_role[]) and created_by=auth.uid());
create policy records_update on public.audit_records for update to authenticated
 using(public.has_store_role(store_id,array['admin','employee']::public.app_role[]))
 with check(public.has_store_role(store_id,array['admin','employee']::public.app_role[]));
create policy records_delete on public.audit_records for delete to authenticated
 using(public.has_store_role(store_id,array['admin']::public.app_role[]));

-- Protect tenant links and auth-only fields from direct client manipulation.
revoke update on public.stores from authenticated;
grant update(name,currency,monthly_production_target,cmv_warning_percent) on public.stores to authenticated;
revoke insert,update,delete on public.store_members from authenticated;
revoke select on public.profiles from authenticated;
grant select(id,user_id,username,username_normalized,display_name,created_at,updated_at) on public.profiles to authenticated;
revoke execute on function public.is_store_member(uuid) from public,anon;
revoke execute on function public.has_store_role(uuid,public.app_role[]) from public,anon;
grant execute on function public.is_store_member(uuid),public.has_store_role(uuid,public.app_role[]) to authenticated;

alter table public.audit_logs add column record_id bigint;
create or replace function public.record_audit_change() returns trigger
language plpgsql security invoker set search_path='' as $$
begin
 if TG_OP='UPDATE' then
  if NEW.store_id <> OLD.store_id or NEW.created_by <> OLD.created_by then raise exception 'Immutable record ownership'; end if;
  NEW.updated_at=now();
  if NEW.kind='recipe' then NEW.payload=jsonb_set(NEW.payload,'{version}',to_jsonb(coalesce((OLD.payload->>'version')::integer,1)+1)); end if;
 end if;
 insert into public.audit_logs(store_id,actor_id,entity_type,record_id,action,before_data,after_data,created_by)
 values(coalesce(NEW.store_id,OLD.store_id),auth.uid(),coalesce(NEW.kind,OLD.kind),coalesce(NEW.id,OLD.id),lower(TG_OP),
 case when TG_OP<>'INSERT' then OLD.payload else null end,
 case when TG_OP<>'DELETE' then NEW.payload else null end,auth.uid());
 if TG_OP='DELETE' then return OLD; end if;
 return NEW;
end; $$;
create trigger records_audit before insert or update or delete on public.audit_records
for each row execute function public.record_audit_change();

-- Atomic restore, deterministic old-to-new ID mapping, repeated files are safe.
create or replace function public.import_records(p_store uuid,p_batch text,p_records jsonb) returns integer
language plpgsql security invoker set search_path='' as $$
declare item jsonb; mapped jsonb='{}'; row_id bigint; key text; data jsonb; entry jsonb; entries jsonb; imported integer=0; field text;
begin
 if not public.has_store_role(p_store,array['admin']::public.app_role[]) then raise exception 'Forbidden'; end if;
 if jsonb_typeof(p_records)<>'array' or jsonb_array_length(p_records)>1000 or p_batch !~ '^[a-f0-9]{64}$' then raise exception 'Invalid backup'; end if;
 perform pg_advisory_xact_lock(hashtextextended(p_store::text||p_batch,0));
 for item in select value from jsonb_array_elements(p_records) loop
  key=p_batch||':'||(item->>'id');
  select id into row_id from public.audit_records where store_id=p_store and legacy_key=key;
  if row_id is null then
   insert into public.audit_records(store_id,kind,payload,legacy_key)
    values(p_store,item->>'kind',item->'payload',key) returning id into row_id;
   imported=imported+1;
  end if;
  mapped=mapped||jsonb_build_object(item->>'id',row_id);
 end loop;
 -- Only rewrite a newly imported batch; retries leave records untouched.
 if imported>0 then
  for item in select value from jsonb_array_elements(p_records) loop
   data=item->'payload';
   foreach field in array array['recipeId','packagingId','productId'] loop
    if data ? field and data->>field <> '0' and data->>field <> '' then
     if not mapped ? (data->>field) then raise exception 'Missing reference'; end if;
     data=jsonb_set(data,array[field],mapped->(data->>field));
    end if;
   end loop;
   if item->>'kind'='recipe' then
    entries='[]';
    for entry in select value from jsonb_array_elements(coalesce(data->'items','[]')) loop
     field=case when entry ? 'subrecipeId' and entry->>'subrecipeId' is not null then 'subrecipeId' else 'ingredientId' end;
     if not mapped ? (entry->>field) then raise exception 'Missing recipe reference'; end if;
     entries=entries||jsonb_build_array(jsonb_set(entry,array[field],mapped->(entry->>field)));
    end loop;
    data=jsonb_set(data,'{items}',entries);
   end if;
   update public.audit_records set payload=data where store_id=p_store and id=(mapped->>(item->>'id'))::bigint;
  end loop;
 end if;
 return imported;
end; $$;
revoke all on function public.import_records(uuid,text,jsonb) from public,anon;
grant execute on function public.import_records(uuid,text,jsonb) to authenticated;
